name: sap
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=10.2
  - numpy=1.18.1
  - matplotlib=3.4.3
  - pyyaml=5.3.1
  - scipy=1.4.1
  - tqdm=4.54.0
  - trimesh=3.8.14
  - igl=2.2.1
  - tensorboard=2.6.0
  - pip

